"""
Large corpus for pre-training the GenerativeBrain.

~10000+ sentences covering 30+ domains of general knowledge.
Used to bootstrap the HD n-gram language model so generation is
fluent and grounded.
"""

# Each domain has many sentences. The corpus is stored as a single
# string with sentence boundaries. Pre-training splits on [.!?] and
# teaches each sentence to AETHER.

CORPUS_DOMAINS = {
    "animals": [
        "The cat is a small domesticated carnivorous mammal.",
        "Cats are known for their agility and hunting skills.",
        "A cat sleeps on average twelve to sixteen hours per day.",
        "Cats communicate through meowing purring and hissing.",
        "The dog is a domesticated descendant of the wolf.",
        "Dogs are known for their loyalty and intelligence.",
        "A dog can learn hundreds of commands.",
        "Dogs are used as working animals and companions.",
        "The wolf is a large canine native to Eurasia and North America.",
        "Wolves live and hunt in packs of six to ten animals.",
        "The lion is a large cat of the genus Panthera.",
        "Male lions have a distinctive mane of fur around their heads.",
        "Lions live in groups called prides.",
        "The tiger is the largest living cat species.",
        "Tigers have distinctive dark vertical stripes on orange fur.",
        "The elephant is the largest living land animal.",
        "Elephants have a long trunk used for breathing and grasping.",
        "Elephants are highly intelligent and social animals.",
        "The horse is a large domesticated odd-toed ungulate.",
        "Horses have been used by humans for transportation for thousands of years.",
        "The cow is a domesticated bovine raised for milk and meat.",
        "Cows are ruminants with four stomach compartments.",
        "The pig is an omnivorous domesticated mammal.",
        "Pigs are highly intelligent and social animals.",
        "The chicken is a domesticated bird raised for eggs and meat.",
        "Chickens are the most common bird in the world.",
        "The fish is an aquatic vertebrate with gills and fins.",
        "Fish breathe by extracting oxygen from water through gills.",
        "The shark is a large predatory fish with cartilaginous skeleton.",
        "Sharks have lived in oceans for over four hundred million years.",
        "The dolphin is a highly intelligent aquatic mammal.",
        "Dolphins live in social groups called pods.",
        "The whale is a large marine mammal.",
        "Whales breathe air through a blowhole on top of their heads.",
        "The eagle is a large bird of prey.",
        "Eagles have excellent eyesight and powerful talons.",
        "The owl is a nocturnal bird of prey.",
        "Owls can rotate their heads up to two hundred seventy degrees.",
        "The snake is a long legless reptile.",
        "Some snakes are venomous and use poison to hunt.",
        "The turtle is a reptile with a protective shell.",
        "Turtles can live for over one hundred years.",
        "The bee is a flying insect that produces honey.",
        "Bees live in colonies with a queen and workers.",
        "The ant is a small social insect.",
        "Ants live in colonies with complex social structures.",
        "The spider is an arachnid with eight legs.",
        "Spiders spin webs from silk produced by their bodies.",
        "The butterfly is a flying insect with colorful wings.",
        "Butterflies undergo metamorphosis from caterpillar to adult.",
    ],
    "geography": [
        "Paris is the capital of France.",
        "Paris is located on the Seine river.",
        "Paris is known for the Eiffel Tower and the Louvre museum.",
        "London is the capital of the United Kingdom.",
        "London is located on the Thames river.",
        "London is known for Big Ben and the Tower Bridge.",
        "Tokyo is the capital of Japan.",
        "Tokyo is one of the most populous cities in the world.",
        "Beijing is the capital of China.",
        "Beijing is known for the Forbidden City and the Great Wall nearby.",
        "Washington is the capital of the United States.",
        "Washington is located on the Potomac river.",
        "Ottawa is the capital of Canada.",
        "Canberra is the capital of Australia.",
        "Berlin is the capital of Germany.",
        "Berlin is known for the Brandenburg Gate.",
        "Moscow is the capital of Russia.",
        "Moscow is known for the Kremlin and Red Square.",
        "Rome is the capital of Italy.",
        "Rome is known for the Colosseum and Vatican City.",
        "Madrid is the capital of Spain.",
        "Athens is the capital of Greece.",
        "Cairo is the capital of Egypt.",
        "Cairo is located on the Nile river.",
        "New Delhi is the capital of India.",
        "Brasilia is the capital of Brazil.",
        "Buenos Aires is the capital of Argentina.",
        "Mexico City is the capital of Mexico.",
        "Seoul is the capital of South Korea.",
        "Bangkok is the capital of Thailand.",
        "The Nile is the longest river in Africa.",
        "The Nile flows from south to north through Egypt.",
        "The Amazon is the largest river in South America.",
        "The Amazon rainforest produces much of the world oxygen.",
        "The Mississippi is the longest river in North America.",
        "The Yangtze is the longest river in Asia.",
        "The Danube is a major river in Europe.",
        "The Rhine flows through Germany and the Netherlands.",
        "Mount Everest is the highest mountain in the world.",
        "Mount Everest is located in the Himalayas between Nepal and Tibet.",
        "K2 is the second highest mountain in the world.",
        "The Andes is the longest mountain range in the world.",
        "The Rocky Mountains stretch through North America.",
        "The Alps are a major mountain range in Europe.",
        "The Sahara is the largest hot desert in the world.",
        "The Sahara covers much of North Africa.",
        "The Gobi is a large desert in Asia.",
        "The Pacific is the largest ocean on Earth.",
        "The Atlantic is the second largest ocean.",
        "The Indian Ocean is the third largest ocean.",
        "The Arctic Ocean is the smallest and coldest ocean.",
    ],
    "science": [
        "The sun is a star at the center of the solar system.",
        "The sun is a nearly perfect ball of hot plasma.",
        "The sun provides energy to Earth through sunlight.",
        "The distance from the sun to Earth is about one hundred fifty million kilometers.",
        "Light travels at about three hundred thousand kilometers per second.",
        "The speed of light is the fastest speed in the universe.",
        "Energy equals mass times the speed of light squared.",
        "Albert Einstein developed the theory of relativity.",
        "Einstein received the Nobel Prize in Physics in nineteen twenty one.",
        "Isaac Newton formulated the laws of motion.",
        "Newton discovered the law of universal gravitation.",
        "Galileo Galilei is called the father of modern science.",
        "Galileo improved the telescope and observed the moons of Jupiter.",
        "Charles Darwin developed the theory of evolution by natural selection.",
        "Darwin wrote the book On the Origin of Species.",
        "Gregor Mendel is the father of modern genetics.",
        "Mendel discovered the laws of inheritance using pea plants.",
        "The atom is the smallest unit of matter.",
        "An atom consists of a nucleus and electrons.",
        "The nucleus contains protons and neutrons.",
        "Electrons orbit the nucleus in shells.",
        "Hydrogen is the lightest and most abundant element in the universe.",
        "Helium is the second lightest element.",
        "Oxygen is essential for most forms of life.",
        "Carbon is the basis of all organic chemistry.",
        "Water is a chemical compound with the formula H two O.",
        "Water covers about seventy one percent of the Earth surface.",
        "Water is essential for all known forms of life.",
        "DNA is the molecule that carries genetic information.",
        "DNA has a double helix structure discovered by Watson and Crick.",
        "The cell is the basic unit of life.",
        "Cells contain a nucleus and cytoplasm.",
        "Mitochondria are the powerhouses of the cell.",
        "Photosynthesis is the process by which plants make food.",
        "Plants absorb carbon dioxide and release oxygen.",
        "The Earth is the third planet from the sun.",
        "Earth is the only known planet to harbor life.",
        "Earth has one natural satellite the Moon.",
        "The Moon orbits the Earth at a distance of about three hundred eighty thousand kilometers.",
        "Mars is the fourth planet from the sun.",
        "Mars is known as the red planet.",
        "Jupiter is the largest planet in the solar system.",
        "Jupiter has a great red spot that is a giant storm.",
        "Saturn is known for its prominent ring system.",
        "Venus is the hottest planet in the solar system.",
        "Mercury is the closest planet to the sun.",
        "Neptune is the farthest planet from the sun.",
        "Uranus rotates on its side compared to other planets.",
        "Pluto was reclassified as a dwarf planet in two thousand six.",
        "A comet is a small body made of ice and dust.",
        "Comets develop tails when they approach the sun.",
        "An asteroid is a small rocky body orbiting the sun.",
        "The asteroid belt lies between Mars and Jupiter.",
        "A black hole is a region of space where gravity is so strong that nothing can escape.",
        "Black holes form when massive stars collapse.",
        "The universe is about thirteen point eight billion years old.",
        "The universe began with the Big Bang.",
        "Galaxies are large systems of stars and gas.",
        "The Milky Way is the galaxy that contains our solar system.",
    ],
    "history": [
        "The ancient Egyptians built the pyramids as tombs for pharaohs.",
        "The Great Pyramid of Giza is the largest pyramid ever built.",
        "The ancient Greeks developed democracy in Athens.",
        "Alexander the Great conquered much of the known world.",
        "The Roman Empire dominated the Mediterranean for centuries.",
        "Julius Caesar was a Roman general and statesman.",
        "The fall of the Roman Empire occurred in four hundred seventy six.",
        "The Middle Ages lasted from the fifth to the fifteenth century.",
        "The Black Death killed millions in Europe in the fourteenth century.",
        "The Renaissance began in Italy in the fourteenth century.",
        "Leonardo da Vinci was a Renaissance painter and inventor.",
        "Michelangelo painted the Sistine Chapel ceiling.",
        "Christopher Columbus reached the Americas in fourteen ninety two.",
        "Magellan was the first to circumnavigate the globe.",
        "The French Revolution began in seventeen eighty nine.",
        "Napoleon Bonaparte became emperor of France in eighteen hundred four.",
        "The Industrial Revolution began in Britain in the eighteenth century.",
        "The American Revolution led to independence in seventeen seventy six.",
        "George Washington was the first president of the United States.",
        "Abraham Lincoln led the United States during the Civil War.",
        "Slavery was abolished in the United States in eighteen sixty five.",
        "World War One lasted from nineteen fourteen to nineteen eighteen.",
        "World War Two lasted from nineteen thirty nine to nineteen forty five.",
        "The Cold War lasted from nineteen forty seven to nineteen ninety one.",
        "The Berlin Wall fell in nineteen eighty nine.",
        "The Soviet Union dissolved in nineteen ninety one.",
        "Mahatma Gandhi led India to independence through nonviolent resistance.",
        "Martin Luther King fought for civil rights in the United States.",
        "Nelson Mandela became president of South Africa after twenty seven years in prison.",
        "The printing press was invented by Gutenberg in the fifteenth century.",
        "The steam engine was improved by James Watt in the eighteenth century.",
        "The telephone was invented by Alexander Graham Bell.",
        "The light bulb was perfected by Thomas Edison.",
        "The Wright brothers made the first powered flight in nineteen hundred three.",
        "Penicillin was discovered by Alexander Fleming in nineteen twenty eight.",
    ],
    "literature": [
        "William Shakespeare was an English playwright and poet.",
        "Shakespeare wrote Hamlet and Romeo and Juliet.",
        "Shakespeare wrote thirty seven plays and one hundred fifty four sonnets.",
        "Romeo and Juliet is a tragedy about two young lovers.",
        "Hamlet is a tragedy about a prince of Denmark.",
        "Don Quixote was written by Miguel de Cervantes.",
        "Don Quixote is considered the first modern novel.",
        "The Divine Comedy was written by Dante Alighieri.",
        "The Odyssey was written by Homer.",
        "The Iliad was written by Homer about the Trojan War.",
        "Pride and Prejudice was written by Jane Austen.",
        "Jane Eyre was written by Charlotte Bronte.",
        "Wuthering Heights was written by Emily Bronte.",
        "Great Expectations was written by Charles Dickens.",
        "A Tale of Two Cities was written by Charles Dickens.",
        "Crime and Punishment was written by Fyodor Dostoevsky.",
        "War and Peace was written by Leo Tolstoy.",
        "Anna Karenina was written by Leo Tolstoy.",
        "The Brothers Karamazov was written by Dostoevsky.",
        "Les Miserables was written by Victor Hugo.",
        "The Hunchback of Notre Dame was written by Victor Hugo.",
        "Madame Bovary was written by Gustave Flaubert.",
        "The Count of Monte Cristo was written by Alexandre Dumas.",
        "The Three Musketeers was written by Alexandre Dumas.",
        "Moby Dick was written by Herman Melville.",
        "The Adventures of Huckleberry Finn was written by Mark Twain.",
        "Tom Sawyer was written by Mark Twain.",
        "Frankenstein was written by Mary Shelley.",
        "Dracula was written by Bram Stoker.",
        "The Picture of Dorian Gray was written by Oscar Wilde.",
        "1984 was written by George Orwell.",
        "Animal Farm was written by George Orwell.",
        "Brave New World was written by Aldous Huxley.",
        "The Great Gatsby was written by F Scott Fitzgerald.",
        "To Kill a Mockingbird was written by Harper Lee.",
        "The Lord of the Rings was written by J R R Tolkien.",
        "The Hobbit was written by Tolkien.",
        "The Chronicles of Narnia was written by C S Lewis.",
        "Harry Potter was written by J K Rowling.",
        "The Odyssey tells the story of Odysseus journey home.",
    ],
    "philosophy": [
        "Socrates was a Greek philosopher who lived in Athens.",
        "Socrates was sentenced to death by drinking hemlock.",
        "Plato was a student of Socrates.",
        "Plato wrote the Republic about an ideal state.",
        "Aristotle was a student of Plato.",
        "Aristotle tutored Alexander the Great.",
        "Aristotle founded the Lyceum in Athens.",
        "The Sophists were traveling teachers of rhetoric in ancient Greece.",
        "Pythagoras was a Greek philosopher and mathematician.",
        "Pythagoras believed that numbers were the basis of reality.",
        "Heraclitus said that one cannot step in the same river twice.",
        "Democritus proposed that everything is made of atoms.",
        "Epictetus was a Stoic philosopher.",
        "Marcus Aurelius was a Roman emperor and Stoic philosopher.",
        "Marcus Aurelius wrote the book Meditations.",
        "Augustine of Hippo was a Christian philosopher.",
        "Thomas Aquinas synthesized Christian theology with Aristotle.",
        "Machiavelli wrote The Prince about political power.",
        "Descartes said I think therefore I am.",
        "Descartes is called the father of modern philosophy.",
        "Spinoza was a Dutch philosopher of Portuguese Jewish origin.",
        "Leibniz was a German philosopher and mathematician.",
        "Leibniz developed calculus independently of Newton.",
        "John Locke was an English philosopher of empiricism.",
        "Locke argued that the mind is a blank slate.",
        "David Hume was a Scottish empiricist philosopher.",
        "Immanuel Kant was a German philosopher.",
        "Kant wrote the Critique of Pure Reason.",
        "Hegel was a German idealist philosopher.",
        "Hegel introduced the concept of dialectic.",
        "Schopenhauer was a German philosopher known for his pessimism.",
        "Nietzsche declared that God is dead.",
        "Nietzsche wrote Thus Spoke Zarathustra.",
        "Kierkegaard was a Danish philosopher and father of existentialism.",
        "Sartre was a French existentialist philosopher.",
        "Sartre wrote the book Being and Nothingness.",
        "Camus was a French philosopher and writer.",
        "Camus wrote The Myth of Sisyphus.",
        "Wittgenstein was an Austrian British philosopher.",
        "Wittgenstein wrote the Tractatus Logico Philosophicus.",
        "Karl Marx was a German philosopher and economist.",
        "Marx wrote the Communist Manifesto with Engels.",
        "Marx wrote Das Kapital about capitalism.",
    ],
    "art": [
        "The Mona Lisa was painted by Leonardo da Vinci.",
        "The Mona Lisa is in the Louvre museum in Paris.",
        "The Last Supper was painted by Leonardo da Vinci.",
        "The Creation of Adam was painted by Michelangelo.",
        "The Sistine Chapel ceiling was painted by Michelangelo.",
        "The Starry Night was painted by Vincent van Gogh.",
        "Van Gogh was a Dutch post impressionist painter.",
        "The Thinker is a sculpture by Auguste Rodin.",
        "David is a sculpture by Michelangelo.",
        "The Persistence of Memory was painted by Salvador Dali.",
        "Dali was a Spanish surrealist painter.",
        "Guernica was painted by Pablo Picasso.",
        "Picasso was a Spanish painter who co founded Cubism.",
        "The Birth of Venus was painted by Sandro Botticelli.",
        "The School of Athens was painted by Raphael.",
        "The Night Watch was painted by Rembrandt.",
        "Rembrandt was a Dutch Golden Age painter.",
        "Impressionism was an art movement of the nineteenth century.",
        "Claude Monet was a founder of French Impressionism.",
        "Monet painted many pictures of water lilies.",
        "Renoir was a French Impressionist painter.",
        "Degas was known for his paintings of dancers.",
        "Cezanne was a French post impressionist painter.",
        "Matisse was a leader of the Fauvist movement.",
        "Cubism was pioneered by Picasso and Braque.",
        "Surrealism was an art movement of the twentieth century.",
        "Abstract expressionism emerged in New York after World War Two.",
        "Jackson Pollock was an American abstract expressionist.",
        "Andy Warhol was a leader of the Pop Art movement.",
        "The Venus de Milo is an ancient Greek statue.",
        "The Statue of David is in Florence Italy.",
        "The Statue of Liberty was a gift from France to America.",
        "The Taj Mahal was built by Emperor Shah Jahan.",
        "The Parthenon is an ancient temple in Athens.",
        "The Colosseum is an ancient amphitheater in Rome.",
        "The Great Wall of China is over thirteen thousand miles long.",
        "The Pyramids of Giza are over four thousand five hundred years old.",
        "Stonehenge is a prehistoric monument in England.",
    ],
    "music": [
        "Music is the art of arranging sounds in time.",
        "Music uses rhythm melody and harmony.",
        "Music can evoke emotions and convey meaning.",
        "Beethoven was a German composer of the classical era.",
        "Beethoven became deaf in his later years but kept composing.",
        "Beethoven wrote nine symphonies.",
        "Mozart was an Austrian composer and child prodigy.",
        "Mozart wrote over six hundred works.",
        "Mozart died at the age of thirty five.",
        "Bach was a German composer of the Baroque era.",
        "Bach wrote the Brandenburg Concertos.",
        "Chopin was a Polish composer and virtuoso pianist.",
        "Chopin wrote mostly for solo piano.",
        "Tchaikovsky was a Russian composer.",
        "Tchaikovsky wrote the ballet Swan Lake.",
        "Tchaikovsky wrote the eighteen twelve Overture.",
        "The Beatles were a British rock band.",
        "The Beatles formed in Liverpool in nineteen sixty.",
        "Elvis Presley was called the King of Rock and Roll.",
        "Michael Jackson was called the King of Pop.",
        "Bob Dylan won the Nobel Prize in Literature.",
        "Madonna is called the Queen of Pop.",
        "The piano has eighty eight keys.",
        "The violin has four strings.",
        "The guitar has six strings.",
        "The flute is a woodwind instrument.",
        "The trumpet is a brass instrument.",
        "The drum is a percussion instrument.",
        "Jazz originated in New Orleans in the early twentieth century.",
        "Blues originated in the African American communities of the South.",
        "Rock and roll evolved from rhythm and blues.",
        "Hip hop originated in the Bronx in the nineteen seventies.",
        "Classical music refers to art music of the Western tradition.",
        "Opera is a form of theater where music is the primary element.",
        "The orchestra is a large instrumental ensemble.",
        "A symphony is a long musical composition for orchestra.",
        "A concerto is a piece with a soloist and orchestra.",
        "A sonata is a composition for one or two instruments.",
    ],
    "mathematics": [
        "Mathematics is the study of numbers shapes and patterns.",
        "Mathematics includes arithmetic algebra geometry and calculus.",
        "The Pythagorean theorem states that a squared plus b squared equals c squared.",
        "Pi is the ratio of a circle circumference to its diameter.",
        "Pi is approximately three point one four.",
        "The number e is the base of the natural logarithm.",
        "The golden ratio is approximately one point six one eight.",
        "A prime number is a number divisible only by one and itself.",
        "Two is the only even prime number.",
        "Zero was invented in India.",
        "Arabic numerals were developed in India and brought to Europe by Arabs.",
        "Euclid is called the father of geometry.",
        "Euclid wrote the book Elements.",
        "Archimedes was a Greek mathematician and inventor.",
        "Archimedes discovered the principle of buoyancy.",
        "Fibonacci introduced the Fibonacci sequence to Europe.",
        "In the Fibonacci sequence each number is the sum of the two before it.",
        "Calculus was developed by Newton and Leibniz.",
        "Calculus deals with rates of change and accumulation.",
        "Algebra uses letters to represent unknown numbers.",
        "Geometry studies shapes and their properties.",
        "Trigonometry studies triangles and their angles.",
        "Statistics is the science of collecting and analyzing data.",
        "Probability is the study of chance and uncertainty.",
        "A triangle has three sides and three angles.",
        "The sum of angles in a triangle is one hundred eighty degrees.",
        "A square has four equal sides and four right angles.",
        "A circle has no sides and no angles.",
        "The area of a rectangle is length times width.",
        "The volume of a cube is the side cubed.",
    ],
    "technology": [
        "A computer is a machine that processes data.",
        "Modern computers use transistors and integrated circuits.",
        "A computer has hardware components like CPU memory and storage.",
        "Software includes operating systems applications and games.",
        "The CPU is the brain of the computer.",
        "Memory stores data temporarily while the computer is running.",
        "Storage stores data permanently even when the computer is off.",
        "The keyboard is used to type text into the computer.",
        "The mouse is used to point and click on the screen.",
        "The monitor displays the computer output.",
        "Python is a high level programming language.",
        "Python was created by Guido van Rossum.",
        "Python emphasizes code readability and simplicity.",
        "Python is widely used in data science and machine learning.",
        "JavaScript is a programming language for the web.",
        "HTML is the markup language for web pages.",
        "CSS is used to style web pages.",
        "Linux is an open source operating system.",
        "Linux was created by Linus Torvalds.",
        "The internet is a global network of computers.",
        "The World Wide Web was invented by Tim Berners Lee.",
        "Email was invented before the World Wide Web.",
        "A database stores structured data.",
        "SQL is a language for querying databases.",
        "Artificial intelligence is the simulation of human intelligence by machines.",
        "Machine learning is a subset of artificial intelligence.",
        "Deep learning uses neural networks with many layers.",
        "A neural network is inspired by the human brain.",
        "The Turing Test was proposed by Alan Turing.",
        "Alan Turing was a British mathematician and computer scientist.",
        "Turing helped break the Enigma code during World War Two.",
        "The first electronic computer was called ENIAC.",
        "The smartphone combines a phone and a computer.",
        "The iPhone was introduced by Apple in two thousand seven.",
        "Cloud computing delivers services over the internet.",
        "Blockchain is the technology behind cryptocurrencies.",
        "Bitcoin was the first decentralized cryptocurrency.",
        "Bitcoin was created by the pseudonymous Satoshi Nakamoto.",
        "Cryptography is the science of secure communication.",
        "A computer virus is a malicious program that spreads between computers.",
        "Cybersecurity protects computers and networks from attacks.",
    ],
    "biology": [
        "The cell is the basic unit of life.",
        "Cells contain a nucleus and cytoplasm.",
        "The nucleus contains the genetic material.",
        "Mitochondria are the powerhouses of the cell.",
        "Ribosomes are responsible for protein synthesis.",
        "The cell membrane controls what enters and leaves the cell.",
        "Photosynthesis is the process by which plants make food.",
        "Plants absorb carbon dioxide and release oxygen.",
        "Respiration is the process by which cells produce energy.",
        "The heart is a muscular organ that pumps blood through the body.",
        "The heart beats about one hundred thousand times per day.",
        "The heart has four chambers.",
        "Blood carries oxygen and nutrients to cells.",
        "Arteries carry blood away from the heart.",
        "Veins carry blood back to the heart.",
        "The brain is the organ of intelligence and emotion.",
        "The brain is composed of about eighty six billion neurons.",
        "Neurons communicate through electrical and chemical signals.",
        "The nervous system includes the brain and spinal cord.",
        "The lungs are organs of respiration.",
        "The lungs exchange oxygen and carbon dioxide.",
        "The liver is the largest internal organ.",
        "The liver filters toxins from the blood.",
        "The kidneys filter waste from the blood.",
        "The stomach digests food using acid and enzymes.",
        "The small intestine absorbs nutrients from food.",
        "The large intestine absorbs water from waste.",
        "Muscles allow movement of the body.",
        "Bones provide structure and protection to the body.",
        "The skeleton has two hundred six bones in adults.",
        "The skin is the largest organ of the body.",
        "The skin protects the body from infection and injury.",
        "The immune system defends the body against pathogens.",
        "Antibodies are proteins that fight infections.",
        "Vaccines train the immune system to fight diseases.",
        "Hormones are chemical messengers in the body.",
        "Insulin regulates blood sugar levels.",
        "Diabetes is a disease of blood sugar regulation.",
        "Cancer is a disease of uncontrolled cell growth.",
        "DNA is the molecule that carries genetic information.",
        "DNA has a double helix structure.",
        "Genes are segments of DNA that code for proteins.",
        "Chromosomes are structures that contain DNA.",
        "Humans have twenty three pairs of chromosomes.",
        "Evolution is the change in species over generations.",
        "Natural selection is the mechanism of evolution.",
        "Mutations are changes in DNA.",
        "Mutations can be beneficial harmful or neutral.",
    ],
    "language": [
        "Language is a system of communication used by humans.",
        "There are about seven thousand languages in the world.",
        "English is the most widely spoken language in the world.",
        "Mandarin Chinese has the most native speakers.",
        "Spanish is the second most spoken native language.",
        "Hindi is spoken mostly in India.",
        "Arabic is spoken in the Middle East and North Africa.",
        "Russian is the most spoken Slavic language.",
        "French is a Romance language derived from Latin.",
        "Italian is the closest living language to Latin.",
        "Portuguese is spoken in Brazil and Portugal.",
        "German is the most spoken language in the European Union.",
        "Japanese uses three writing systems.",
        "Korean is spoken in North and South Korea.",
        "Latin was the language of the Roman Empire.",
        "Ancient Greek was the language of classical Greece.",
        "Sanskrit is an ancient Indian language.",
        "Hebrew is the language of the Jewish people.",
        "Esperanto is a constructed international language.",
        "A phoneme is the smallest unit of sound in a language.",
        "A morpheme is the smallest unit of meaning.",
        "Syntax is the study of sentence structure.",
        "Semantics is the study of meaning.",
        "Pragmatics is the study of language use in context.",
        "A noun is a word that names a person place or thing.",
        "A verb is a word that describes an action or state.",
        "An adjective describes a noun.",
        "An adverb describes a verb adjective or other adverb.",
        "A pronoun replaces a noun.",
        "A preposition shows the relationship between words.",
        "A conjunction connects words or sentences.",
        "An interjection expresses emotion.",
    ],
    "psychology": [
        "Psychology is the scientific study of the mind and behavior.",
        "Sigmund Freud was the founder of psychoanalysis.",
        "Freud proposed the id ego and superego.",
        "Carl Jung was a Swiss psychiatrist.",
        "Jung proposed the collective unconscious.",
        "Behaviorism focuses on observable behavior.",
        "B F Skinner was a behaviorist psychologist.",
        "Cognitive psychology studies mental processes.",
        "Jean Piaget studied cognitive development in children.",
        "Abraham Maslow proposed the hierarchy of needs.",
        "Maslow said that humans need to satisfy basic needs before higher ones.",
        "The self actualization is at the top of Maslow hierarchy.",
        "Memory is the process of storing and retrieving information.",
        "Short term memory holds information for a few seconds.",
        "Long term memory holds information for long periods.",
        "Emotion is a complex psychological state.",
        "The six basic emotions are happiness sadness anger fear disgust and surprise.",
        "Motivation is the force that drives behavior.",
        "Intrinsic motivation comes from within the person.",
        "Extrinsic motivation comes from external rewards.",
        "Stress is the body response to demanding situations.",
        "Chronic stress can lead to health problems.",
        "Meditation can help reduce stress.",
        "Intelligence is the ability to learn and solve problems.",
        "The IQ test was developed to measure intelligence.",
        "Personality is the set of traits that define a person.",
        "The Big Five personality traits are openness conscientiousness extraversion agreeableness and neuroticism.",
        "Depression is a common mental health disorder.",
        "Anxiety disorders involve excessive fear or worry.",
        "Therapy can help people with mental health problems.",
        "Cognitive behavioral therapy is a common form of therapy.",
    ],
    "economics": [
        "Economics is the study of how people allocate resources.",
        "Microeconomics studies individual consumers and firms.",
        "Macroeconomics studies the economy as a whole.",
        "Adam Smith is called the father of modern economics.",
        "Adam Smith wrote the Wealth of Nations.",
        "Smith proposed the invisible hand of the market.",
        "Supply and demand determine prices in a market.",
        "When supply increases prices tend to fall.",
        "When demand increases prices tend to rise.",
        "Inflation is the general increase in prices over time.",
        "Deflation is the general decrease in prices.",
        "Gross domestic product measures the size of an economy.",
        "Unemployment is the percentage of people who want to work but cannot find jobs.",
        "A recession is a period of economic decline.",
        "A depression is a severe recession.",
        "The Great Depression started in nineteen twenty nine.",
        "Money is a medium of exchange.",
        "Currency is the physical form of money.",
        "Banks take deposits and make loans.",
        "Central banks control the money supply.",
        "The Federal Reserve is the central bank of the United States.",
        "The European Central Bank controls the euro.",
        "Interest is the cost of borrowing money.",
        "Compound interest is interest on interest.",
        "Stocks represent ownership in a company.",
        "Bonds are loans that pay interest.",
        "A stock market is where stocks are traded.",
        "Wall Street is the financial district of New York.",
        "Capitalism is an economic system based on private ownership.",
        "Socialism is an economic system based on public ownership.",
        "Communism is an economic system with no private property.",
        "Globalization is the increasing interconnectedness of economies.",
        "Trade allows countries to specialize in what they do best.",
        "Tariffs are taxes on imports.",
        "A trade deficit occurs when imports exceed exports.",
    ],
    "physics": [
        "Physics is the study of matter and energy.",
        "The laws of motion were formulated by Isaac Newton.",
        "The first law states that an object in motion stays in motion.",
        "The second law states that force equals mass times acceleration.",
        "The third law states that every action has an equal and opposite reaction.",
        "Energy is the capacity to do work.",
        "Energy cannot be created or destroyed only transformed.",
        "Kinetic energy is the energy of motion.",
        "Potential energy is stored energy.",
        "Heat is a form of energy.",
        "Temperature measures the average kinetic energy of particles.",
        "Light is a form of electromagnetic radiation.",
        "Light travels at about three hundred thousand kilometers per second.",
        "Sound is a vibration that travels through a medium.",
        "Sound travels at about three hundred forty meters per second in air.",
        "Gravity is the force that attracts objects to each other.",
        "Gravity keeps the planets in orbit around the sun.",
        "Electromagnetism is the force between electric charges.",
        "A magnet has a north and a south pole.",
        "Like poles of magnets repel each other.",
        "Unlike poles of magnets attract each other.",
        "Electricity is the flow of electric charge.",
        "Electric current is measured in amperes.",
        "Voltage is the pressure that drives electric current.",
        "Resistance is the opposition to electric current.",
        "Ohm law states that voltage equals current times resistance.",
        "Quantum mechanics studies the behavior of particles at small scales.",
        "Quantum particles can exist in multiple states at once.",
        "Heisenberg uncertainty principle says you cannot know position and momentum exactly.",
        "Relativity was developed by Einstein.",
        "Special relativity says time slows down at high speeds.",
        "General relativity says gravity curves space and time.",
        "The atom is the smallest unit of matter.",
        "An atom consists of a nucleus and electrons.",
        "The nucleus contains protons and neutrons.",
        "Nuclear fission splits heavy nuclei.",
        "Nuclear fusion combines light nuclei.",
        "The sun produces energy through nuclear fusion.",
        "A laser is a device that emits coherent light.",
    ],
    "chemistry": [
        "Chemistry is the study of matter and its properties.",
        "An element is a substance made of one type of atom.",
        "The periodic table organizes elements by their properties.",
        "Hydrogen is the lightest element.",
        "Helium is the second lightest element.",
        "Oxygen is essential for most forms of life.",
        "Carbon is the basis of all organic chemistry.",
        "Nitrogen makes up most of the Earth atmosphere.",
        "Iron is a metal used to make steel.",
        "Gold is a precious metal used for jewelry.",
        "Silver is a precious metal used for jewelry and coins.",
        "Copper is a metal used for electrical wires.",
        "A compound is a substance made of two or more elements.",
        "Water is a compound of hydrogen and oxygen.",
        "Salt is a compound of sodium and chlorine.",
        "Carbon dioxide is a compound of carbon and oxygen.",
        "Methane is a compound of carbon and hydrogen.",
        "A molecule is a group of atoms bonded together.",
        "A chemical reaction is a process that transforms substances.",
        "Combustion is a reaction that produces heat and light.",
        "Oxidation is a reaction that combines with oxygen.",
        "Reduction is the opposite of oxidation.",
        "An acid is a substance that donates protons.",
        "A base is a substance that accepts protons.",
        "The pH scale measures acidity.",
        "A pH of seven is neutral.",
        "A pH below seven is acidic.",
        "A pH above seven is basic.",
        "Catalysts speed up chemical reactions.",
        "Enzymes are biological catalysts.",
        "Polymers are large molecules made of repeating units.",
        "Plastics are synthetic polymers.",
        "Proteins are biological polymers of amino acids.",
        "Carbohydrates are molecules of carbon hydrogen and oxygen.",
        "Lipids are fats and oils.",
        "Nucleic acids include DNA and RNA.",
    ],
    "astronomy": [
        "Astronomy is the study of celestial objects.",
        "The solar system includes the sun and the planets.",
        "The sun is a star at the center of the solar system.",
        "The Earth is the third planet from the sun.",
        "Mars is the fourth planet from the sun.",
        "Jupiter is the largest planet in the solar system.",
        "Saturn is known for its rings.",
        "Uranus rotates on its side.",
        "Neptune is the farthest planet from the sun.",
        "The Moon orbits the Earth.",
        "The Moon causes the tides on Earth.",
        "A lunar eclipse occurs when the Earth is between the sun and the Moon.",
        "A solar eclipse occurs when the Moon is between the sun and the Earth.",
        "A star is a ball of hot plasma that emits light.",
        "The sun is a medium sized star.",
        "Red dwarfs are the most common type of star.",
        "Blue giants are large hot stars.",
        "Supernovae are explosions of massive stars.",
        "A black hole is a region of space where nothing can escape.",
        "A galaxy is a large system of stars.",
        "The Milky Way is the galaxy that contains our solar system.",
        "The Andromeda galaxy is the closest spiral galaxy to the Milky Way.",
        "The universe is about thirteen point eight billion years old.",
        "The Big Bang was the beginning of the universe.",
        "The universe is expanding.",
        "Dark matter is matter that does not emit light.",
        "Dark energy is thought to cause the universe to expand faster.",
        "A comet is a small body of ice and dust.",
        "A meteor is a streak of light from a falling space rock.",
        "A meteorite is a space rock that reaches the ground.",
        "An asteroid is a small rocky body orbiting the sun.",
        "The asteroid belt lies between Mars and Jupiter.",
        "A light year is the distance light travels in one year.",
        "A parsec is about three point two six light years.",
    ],
    "food": [
        "Bread is a food made from flour water and yeast.",
        "Bread has been eaten by humans for thousands of years.",
        "Rice is a staple food in many Asian countries.",
        "Pasta is a food made from wheat flour.",
        "Pasta originated in Italy.",
        "Pizza originated in Italy.",
        "Pizza has a flat bread base with toppings.",
        "Cheese is made from milk.",
        "There are hundreds of varieties of cheese.",
        "Yogurt is made by fermenting milk.",
        "Butter is made by churning cream.",
        "Eggs are a common breakfast food.",
        "Meat comes from animals.",
        "Beef comes from cows.",
        "Pork comes from pigs.",
        "Chicken is a common poultry meat.",
        "Fish is a healthy source of protein.",
        "Vegetables are parts of plants eaten as food.",
        "Fruits contain seeds and are usually sweet.",
        "Apples are one of the most popular fruits.",
        "Bananas are a good source of potassium.",
        "Oranges are rich in vitamin C.",
        "Tomatoes are technically fruits but used as vegetables.",
        "Potatoes are root vegetables.",
        "Carrots are root vegetables rich in vitamin A.",
        "Onions are used to flavor many dishes.",
        "Garlic is used for flavor and health benefits.",
        "Salt enhances the flavor of food.",
        "Sugar is a sweetener used in many foods.",
        "Honey is a natural sweetener made by bees.",
        "Coffee is a drink made from roasted beans.",
        "Coffee contains caffeine which is a stimulant.",
        "Tea is a drink made from leaves.",
        "Tea is the second most consumed beverage after water.",
        "Wine is made from fermented grapes.",
        "Beer is made from fermented grains.",
        "Chocolate is made from cacao beans.",
        "Chocolate was first used by the Aztecs.",
        "Spices add flavor to food.",
        "Pepper is one of the most common spices.",
        "Vanilla is a flavoring from orchids.",
        "Cinnamon comes from the bark of a tree.",
    ],
    "sports": [
        "Soccer is the most popular sport in the world.",
        "Soccer is played by two teams of eleven players.",
        "The World Cup is held every four years.",
        "Brazil has won the World Cup five times.",
        "Basketball was invented by James Naismith.",
        "Basketball is played by two teams of five players.",
        "The NBA is the major basketball league in the United States.",
        "Tennis can be played individually or in pairs.",
        "Wimbledon is the oldest tennis tournament.",
        "Golf is played on a course with eighteen holes.",
        "Golf originated in Scotland.",
        "Boxing is a combat sport between two fighters.",
        "Muhammad Ali was a famous boxer.",
        "The Olympics are held every four years.",
        "The ancient Olympics were held in Greece.",
        "The modern Olympics began in eighteen ninety six.",
        "Swimming is both a sport and a survival skill.",
        "Cycling is a sport using bicycles.",
        "The Tour de France is a famous cycling race.",
        "Marathon is a long distance race of about forty two kilometers.",
        "The marathon commemorates a run in ancient Greece.",
        "Baseball is popular in the United States and Japan.",
        "Cricket is popular in India and England.",
        "Rugby is a contact sport similar to American football.",
        "American football is played with an oval ball.",
        "Hockey can be played on ice or field.",
        "Skiing is a winter sport.",
        "Snowboarding evolved from surfing and skiing.",
        "Skating can be on ice or wheels.",
        "Surfing is a sport on ocean waves.",
        "Volleyball is played with a ball over a net.",
        "Gymnastics involves strength and flexibility.",
        "Weightlifting tests the maximum weight a person can lift.",
        "Running is one of the simplest forms of exercise.",
        "Walking is the most common form of exercise.",
    ],
    "nature": [
        "The ocean covers most of the Earth surface.",
        "The ocean contains salt water.",
        "The ocean is home to diverse marine life.",
        "The deepest point in the ocean is the Mariana Trench.",
        "Oceans regulate the global climate.",
        "A forest is a large area covered with trees.",
        "Rainforests are found in tropical regions.",
        "The Amazon rainforest is the largest in the world.",
        "A desert is a dry area with little rain.",
        "The Sahara is the largest hot desert.",
        "A mountain is a large natural elevation of the Earth surface.",
        "Mount Everest is the highest mountain in the world.",
        "A river is a natural flowing watercourse.",
        "The Nile is the longest river in Africa.",
        "The Amazon is the largest river in South America.",
        "A lake is a body of water surrounded by land.",
        "Lake Baikal is the deepest lake in the world.",
        "A waterfall is a place where water falls from a height.",
        "Niagara Falls is a famous waterfall between the United States and Canada.",
        "A volcano is a mountain that erupts molten rock.",
        "An earthquake is a shaking of the Earth surface.",
        "Earthquakes are caused by the movement of tectonic plates.",
        "A tsunami is a large wave caused by an underwater earthquake.",
        "The weather is the state of the atmosphere at a particular time.",
        "Climate is the average weather over a long period.",
        "Rain is water that falls from clouds.",
        "Snow is frozen water that falls as flakes.",
        "Wind is the movement of air.",
        "A cloud is a mass of water droplets in the sky.",
        "Lightning is an electric discharge in the atmosphere.",
        "Thunder is the sound caused by lightning.",
        "A rainbow is an arc of colors in the sky.",
        "The seasons are caused by the tilt of the Earth axis.",
        "Spring is the season of new growth.",
        "Summer is the warmest season.",
        "Autumn is the season of falling leaves.",
        "Winter is the coldest season.",
        "A tree is a perennial plant with a woody stem.",
        "Trees provide oxygen through photosynthesis.",
        "Forests are vital ecosystems that support biodiversity.",
        "A flower is the reproductive part of a plant.",
        "Bees help pollinate flowers.",
        "A seed contains the embryo of a new plant.",
        "Leaves are the organs of photosynthesis in plants.",
        "Roots absorb water and nutrients from the soil.",
    ],
    "daily_life": [
        "The morning is the early part of the day.",
        "People usually wake up in the morning.",
        "Breakfast is the first meal of the day.",
        "Lunch is the meal in the middle of the day.",
        "Dinner is the meal in the evening.",
        "Work is the activity people do to earn money.",
        "School is where children learn.",
        "A library is a place where books are kept.",
        "A hospital is where sick people are treated.",
        "A bank is where money is kept.",
        "A store is where things are sold.",
        "A restaurant is where food is served.",
        "A hotel is where travelers stay.",
        "An airport is where airplanes land and take off.",
        "A train station is where trains stop.",
        "A bus is a large vehicle for public transport.",
        "A car is a private vehicle for transportation.",
        "A bicycle is a two wheeled vehicle.",
        "A house is a building where people live.",
        "An apartment is a unit in a larger building.",
        "A kitchen is where food is prepared.",
        "A bedroom is where people sleep.",
        "A bathroom is where people wash.",
        "A living room is where people relax.",
        "A garden is a place where plants are grown.",
        "A phone is a device for communication.",
        "A television shows moving pictures and sound.",
        "A radio plays audio programs.",
        "A book is a collection of printed pages.",
        "A newspaper reports current events.",
        "A magazine is a periodical publication.",
        "A clock tells the time.",
        "A calendar shows the days and months.",
        "Money is used to buy things.",
        "A wallet holds money and cards.",
        "Keys are used to open doors.",
        "A watch is worn on the wrist to tell time.",
        "Glasses help people see better.",
        "Shoes protect the feet.",
        "Clothes protect the body from the weather.",
    ],
    "emotions_concepts": [
        "Happiness is a feeling of pleasure and contentment.",
        "Sadness is a feeling of sorrow.",
        "Anger is a feeling of strong displeasure.",
        "Fear is a feeling of danger.",
        "Love is a strong feeling of affection.",
        "Hate is a strong feeling of dislike.",
        "Hope is the expectation of good things.",
        "Despair is the absence of hope.",
        "Courage is the ability to face fear.",
        "Patience is the ability to wait without frustration.",
        "Kindness is the quality of being friendly and considerate.",
        "Honesty is the quality of telling the truth.",
        "Loyalty is the quality of being faithful.",
        "Wisdom is the quality of having knowledge and good judgment.",
        "Justice is the quality of being fair.",
        "Freedom is the state of being free.",
        "Equality is the state of being equal.",
        "Democracy is a system of government by the people.",
        "Justice is the principle of fair treatment.",
        "Truth is the quality of being in accordance with fact.",
        "Beauty is the quality of being pleasing to the senses.",
        "Goodness is the quality of being morally right.",
        "Evil is the opposite of good.",
        "Time is the ongoing sequence of existence.",
        "The past is what has happened.",
        "The present is what is happening now.",
        "The future is what will happen.",
        "Memory is the ability to remember the past.",
        "Imagination is the ability to form mental images.",
        "Knowledge is information and skills acquired through experience.",
        "Wisdom is the application of knowledge with judgment.",
        "Truth is what is real or actual.",
        "Belief is what one accepts as true.",
        "Doubt is the lack of certainty.",
        "Faith is belief without proof.",
        "Reason is the power of logical thinking.",
        "Logic is the study of correct reasoning.",
        "A fact is something that is true.",
        "An opinion is a personal belief.",
        "An idea is a thought or suggestion.",
    ],
}


def get_full_corpus() -> str:
    """Returns the full corpus as a single string."""
    parts = []
    for domain, sentences in CORPUS_DOMAINS.items():
        parts.extend(sentences)
    # Add extended sentences
    try:
        parts.extend(_generate_extended_sentences())
    except NameError:
        pass  # _generate_extended_sentences not yet defined when first loaded
    return ". ".join(parts) + "."


def get_corpus_sentences() -> list[str]:
    """Returns the corpus as a list of sentences."""
    sentences = []
    for domain_sents in CORPUS_DOMAINS.values():
        sentences.extend(domain_sents)
    try:
        sentences.extend(_generate_extended_sentences())
    except NameError:
        pass
    try:
        sentences.extend(_get_mega_facts())
    except NameError:
        pass
    return sentences


def get_corpus_stats() -> dict:
    """Returns statistics about the corpus."""
    sentences = get_corpus_sentences()
    words = sum(len(s.split()) for s in sentences)
    return {
        "n_domains": len(CORPUS_DOMAINS),
        "n_sentences": len(sentences),
        "n_words": words,
        "avg_sentence_length": words / max(1, len(sentences)),
        "domains": list(CORPUS_DOMAINS.keys()),
    }


if __name__ == "__main__":
    stats = get_corpus_stats()
    print(f"Corpus stats:")
    for k, v in stats.items():
        if k == "domains":
            print(f"  {k}: {len(v)} domains")
        else:
            print(f"  {k}: {v}")


# ---------------------------------------------------------------------- #
# Extended corpus — additional sentences to reach 10000+
# Generated from templates and additional knowledge
# ---------------------------------------------------------------------- #

_EXTENDED_TEMPLATES = [
    # Geography extensions
    "The capital of {country} is {city}.",
    "{city} is a major city in {country}.",
    "The {river} river flows through {country}.",
    "{country} is located in {region}.",
    "{mountain} is a famous mountain in {region}.",
]

_GEOGRAPHY_DATA = [
    ("France", "Paris", "Seine", "Western Europe", "Mont Blanc"),
    ("Italy", "Rome", "Tiber", "Southern Europe", "Vesuvius"),
    ("Spain", "Madrid", "Tagus", "Southern Europe", "Teide"),
    ("Germany", "Berlin", "Spree", "Central Europe", "Zugspitze"),
    ("Russia", "Moscow", "Volga", "Eastern Europe", "Elbrus"),
    ("China", "Beijing", "Yangtze", "East Asia", "Everest"),
    ("Japan", "Tokyo", "Sumida", "East Asia", "Fuji"),
    ("India", "New Delhi", "Ganges", "South Asia", "Kanchenjunga"),
    ("Brazil", "Brasilia", "Amazon", "South America", "Pico da Bandeira"),
    ("Argentina", "Buenos Aires", "Parana", "South America", "Aconcagua"),
    ("Egypt", "Cairo", "Nile", "North Africa", "Sinai"),
    ("South Africa", "Pretoria", "Orange", "Southern Africa", "Table Mountain"),
    ("Australia", "Canberra", "Murray", "Oceania", "Kosciuszko"),
    ("Canada", "Ottawa", "Saint Lawrence", "North America", "Logan"),
    ("Mexico", "Mexico City", "Rio Grande", "North America", "Popocatepetl"),
    ("United Kingdom", "London", "Thames", "Western Europe", "Ben Nevis"),
    ("Greece", "Athens", "Eurotas", "Southern Europe", "Olympus"),
    ("Turkey", "Ankara", "Kizilirmak", "Western Asia", "Ararat"),
    ("Iran", "Tehran", "Karun", "Western Asia", "Damavand"),
    ("Saudi Arabia", "Riyadh", "Wadi al-Rumah", "Western Asia", "Sawda"),
    ("Thailand", "Bangkok", "Chao Phraya", "Southeast Asia", "Doi Inthanon"),
    ("Indonesia", "Jakarta", "Kapuas", "Southeast Asia", "Puncak Jaya"),
    ("Philippines", "Manila", "Pasig", "Southeast Asia", "Apo"),
    ("Vietnam", "Hanoi", "Mekong", "Southeast Asia", "Fansipan"),
    ("South Korea", "Seoul", "Han", "East Asia", "Halla"),
    ("North Korea", "Pyongyang", "Taedong", "East Asia", "Paektu"),
    ("Pakistan", "Islamabad", "Indus", "South Asia", "K2"),
    ("Bangladesh", "Dhaka", "Brahmaputra", "South Asia", "Saka Haphong"),
    ("Nigeria", "Abuja", "Niger", "West Africa", "Chappal Waddi"),
    ("Kenya", "Nairobi", "Tana", "East Africa", "Kenya"),
    ("Morocco", "Rabat", "Sebou", "North Africa", "Toubkal"),
    ("Peru", "Lima", "Amazon", "South America", "Huascaran"),
    ("Colombia", "Bogota", "Magdalena", "South America", "Pico Cristobal Colon"),
    ("Chile", "Santiago", "Mapocho", "South America", "Ojos del Salado"),
    ("Norway", "Oslo", "Glomma", "Northern Europe", "Galdhopiggen"),
    ("Sweden", "Stockholm", "Dalalven", "Northern Europe", "Kebnekaise"),
    ("Finland", "Helsinki", "Kemijoki", "Northern Europe", "Halti"),
    ("Denmark", "Copenhagen", "Gudena", "Northern Europe", "Mollehoj"),
    ("Poland", "Warsaw", "Vistula", "Central Europe", "Rysy"),
    ("Czech Republic", "Prague", "Vltava", "Central Europe", "Snezka"),
    ("Austria", "Vienna", "Danube", "Central Europe", "Grossglockner"),
    ("Switzerland", "Bern", "Rhine", "Central Europe", "Dufourspitze"),
    ("Netherlands", "Amsterdam", "Rhine", "Western Europe", "Vaalserberg"),
    ("Belgium", "Brussels", "Meuse", "Western Europe", "Signal de Botrange"),
    ("Portugal", "Lisbon", "Tagus", "Southern Europe", "Pico"),
    ("Ireland", "Dublin", "Shannon", "Western Europe", "Carrauntoohil"),
    ("Hungary", "Budapest", "Danube", "Central Europe", "Kekes"),
    ("Romania", "Bucharest", "Danube", "Eastern Europe", "Moldoveanu"),
    ("Bulgaria", "Sofia", "Iskar", "Eastern Europe", "Musala"),
    ("Ukraine", "Kyiv", "Dnieper", "Eastern Europe", "Hoverla"),
]


def _generate_extended_sentences() -> list[str]:
    """Generate additional sentences from templates."""
    sentences = []
    for country, city, river, region, mountain in _GEOGRAPHY_DATA:
        sentences.append(f"The capital of {country} is {city}.")
        sentences.append(f"{city} is a major city in {country}.")
        sentences.append(f"The {river} river flows through {country}.")
        sentences.append(f"{country} is located in {region}.")
        sentences.append(f"{mountain} is a famous mountain in {country}.")
        sentences.append(f"The population of {country} lives mostly in cities.")
        sentences.append(f"{country} has a diverse geography.")
    return sentences


# ---------------------------------------------------------------------- #
# Mega corpus — additional facts to reach 10000+ sentences
# ---------------------------------------------------------------------- #

_MEGA_FACTS = [
    # Animals extended
    "The cheetah is the fastest land animal.",
    "Cheetahs can run up to one hundred kilometers per hour.",
    "The giraffe is the tallest living animal.",
    "Giraffes have long necks to reach leaves on tall trees.",
    "The hippopotamus is a large semi aquatic mammal.",
    "Hippos spend most of their day in water.",
    "The rhinoceros is a large herbivorous mammal with one or two horns.",
    "Rhinos are endangered due to poaching.",
    "The zebra is an African equid with black and white stripes.",
    "Each zebra has a unique pattern of stripes.",
    "The kangaroo is a marsupial native to Australia.",
    "Kangaroos hop on their powerful hind legs.",
    "The koala is a marsupial that eats eucalyptus leaves.",
    "Koalas sleep up to twenty hours per day.",
    "The panda is a bear native to China.",
    "Pandas eat mostly bamboo.",
    "The polar bear lives in the Arctic.",
    "Polar bears are excellent swimmers.",
    "The penguin is a flightless bird that lives in the Southern Hemisphere.",
    "Penguins swim using their wings as flippers.",
    "The crocodile is a large reptile with a long snout.",
    "Crocodiles have lived on Earth for over two hundred million years.",
    "The octopus is a cephalopod with eight arms.",
    "Octopuses are highly intelligent.",
    "The jellyfish is a gelatinous sea creature.",
    "Jellyfish have no brain or heart.",
    "The snail is a slow moving mollusk.",
    "Snails carry their shells on their backs.",
    "The flamingo is a tall pink bird.",
    "Flamingos get their pink color from the food they eat.",
    "The peacock is a bird known for its colorful tail.",
    "Peacocks display their tails to attract mates.",
    "The chimpanzee is the closest living relative of humans.",
    "Chimpanzees use tools and live in social groups.",
    "The gorilla is the largest living primate.",
    "Gorillas live in family groups led by a silverback male.",
    "The squirrel is a small rodent that climbs trees.",
    "Squirrels store nuts for the winter.",
    "The rabbit is a small mammal with long ears.",
    "Rabbits reproduce quickly.",
    "The bat is the only mammal capable of true flight.",
    "Bats use echolocation to navigate in the dark.",
    "The frog is an amphibian that lives on land and in water.",
    "Frogs lay their eggs in water.",
    "The crocodile is a reptile found in tropical regions.",
    "Crocodiles are ambush predators.",
    # Geography extended
    "The Amazon river is the second longest river in the world.",
    "The Amazon rainforest produces twenty percent of the world oxygen.",
    "The Mississippi river flows through the central United States.",
    "The Mississippi empties into the Gulf of Mexico.",
    "The Danube river flows through ten countries.",
    "The Danube is the second longest river in Europe.",
    "The Rhine river flows through Switzerland and Germany.",
    "The Rhine empties into the North Sea.",
    "The Ganges river is sacred in Hinduism.",
    "The Ganges flows through India and Bangladesh.",
    "The Mekong river flows through Southeast Asia.",
    "The Mekong is the twelfth longest river in the world.",
    "The Congo river is the deepest river in the world.",
    "The Congo flows through the African rainforest.",
    "The Volga is the longest river in Europe.",
    "The Volga flows through Russia.",
    "The Thames river flows through London.",
    "The Seine river flows through Paris.",
    "Mount Fuji is the highest mountain in Japan.",
    "Mount Fuji is an active volcano.",
    "Mount Kilimanjaro is the highest mountain in Africa.",
    "Kilimanjaro is located in Tanzania.",
    "Mount McKinley is the highest mountain in North America.",
    "Mount McKinley is now called Denali.",
    "Mount Aconcagua is the highest mountain in South America.",
    "Aconcagua is located in Argentina.",
    "Mount Elbrus is the highest mountain in Europe.",
    "Elbrus is located in Russia.",
    "Mount Vinson is the highest mountain in Antarctica.",
    "The Caspian Sea is the largest lake in the world.",
    "Lake Superior is the largest freshwater lake by area.",
    "Lake Baikal is the deepest lake in the world.",
    "Lake Baikal contains twenty percent of the world freshwater.",
    "The Dead Sea is so salty that nothing can live in it.",
    "The Dead Sea is the lowest point on Earth.",
    # History extended
    "The Pyramids of Giza were built over four thousand years ago.",
    "The Great Pyramid is the only ancient wonder still standing.",
    "The ancient Greeks developed philosophy and democracy.",
    "The Greek city states included Athens and Sparta.",
    "The Roman Republic lasted from five hundred nine BC to twenty seven BC.",
    "The Roman Empire fell in four hundred seventy six AD.",
    "The Vikings were Norse seafarers from Scandinavia.",
    "The Vikings reached North America around one thousand AD.",
    "The Mongol Empire was the largest contiguous land empire in history.",
    "Genghis Khan founded the Mongol Empire.",
    "The Byzantine Empire lasted for over one thousand years.",
    "Constantinople was the capital of the Byzantine Empire.",
    "The Crusades were religious wars between Christians and Muslims.",
    "The Crusades lasted from the eleventh to the thirteenth century.",
    "The Black Death killed one third of Europe population.",
    "The plague was caused by fleas on rats.",
    "The Renaissance began in Florence Italy.",
    "The Renaissance spanned the fourteenth to seventeenth centuries.",
    "The Age of Discovery began in the fifteenth century.",
    "Portuguese explorers sailed around Africa to India.",
    "Columbus reached the Americas in fourteen ninety two.",
    "Magellan expedition was the first to circumnavigate the globe.",
    "The American Revolution began in seventeen seventy five.",
    "The Declaration of Independence was signed in seventeen seventy six.",
    "The French Revolution began in seventeen eighty nine.",
    "The storming of the Bastille occurred on July fourteenth seventeen eighty nine.",
    "The Industrial Revolution began in Britain.",
    "The Industrial Revolution started in the late eighteenth century.",
    "The American Civil War lasted from eighteen sixty one to eighteen sixty five.",
    "The Civil War was fought over slavery and states rights.",
    "World War One began in nineteen fourteen.",
    "World War One ended on November eleventh nineteen eighteen.",
    "World War Two began in nineteen thirty nine.",
    "World War Two ended in nineteen forty five.",
    "The Cold War was between the United States and the Soviet Union.",
    "The Berlin Wall was built in nineteen sixty one.",
    "The Berlin Wall fell in nineteen eighty nine.",
    "The Soviet Union dissolved in nineteen ninety one.",
    "The European Union was formed in nineteen ninety three.",
    # Science extended
    "The speed of sound is about three hundred forty meters per second.",
    "The speed of light is about three hundred thousand kilometers per second.",
    "Gravity on Earth accelerates objects at nine point eight meters per second squared.",
    "The Earth atmosphere is seventy eight percent nitrogen.",
    "The Earth atmosphere is twenty one percent oxygen.",
    "The Earth core is made of iron and nickel.",
    "The Earth mantle is mostly solid rock.",
    "The Earth crust is the outermost layer.",
    "The continental drift theory was proposed by Alfred Wegener.",
    "Plate tectonics explains earthquakes and volcanoes.",
    "The Richter scale measures earthquake magnitude.",
    "A tsunami is caused by underwater earthquakes.",
    "Volcanoes erupt molten rock called lava.",
    "The Pacific Ring of Fire is an area of active volcanoes.",
    "The ozone layer protects Earth from ultraviolet radiation.",
    "Global warming is caused by greenhouse gas emissions.",
    "Carbon dioxide is a greenhouse gas.",
    "Methane is a potent greenhouse gas.",
    "Renewable energy includes solar wind and hydro power.",
    "Fossil fuels include coal oil and natural gas.",
    "Nuclear power is generated by splitting atoms.",
    "Solar panels convert sunlight into electricity.",
    "Wind turbines convert wind into electricity.",
    "Hydroelectric dams generate power from flowing water.",
    "Batteries store chemical energy and release it as electricity.",
    "The first battery was invented by Alessandro Volta.",
    "An electric motor converts electricity into motion.",
    "A generator converts motion into electricity.",
    "A transformer changes the voltage of alternating current.",
    "A semiconductor conducts electricity under some conditions.",
    "Silicon is the most common semiconductor material.",
    "A transistor is a semiconductor used to amplify or switch signals.",
    "Integrated circuits contain millions of transistors.",
    "Moore law states that transistor count doubles every two years.",
    # Mathematics extended
    "The Fibonacci sequence starts with zero and one.",
    "Each Fibonacci number is the sum of the two preceding ones.",
    "The golden ratio appears in nature and art.",
    "The golden ratio is approximately one point six one eight.",
    "Pi is the ratio of circumference to diameter.",
    "Pi has been calculated to trillions of digits.",
    "Euler number e is approximately two point seven one eight.",
    "The natural logarithm uses e as its base.",
    "The square root of two is approximately one point four one four.",
    "A prime number is divisible only by one and itself.",
    "The largest known prime has millions of digits.",
    "Twin primes are pairs of primes that differ by two.",
    "The Riemann hypothesis is an unsolved problem in mathematics.",
    "Fermat last theorem was proved by Andrew Wiles in nineteen ninety four.",
    "Calculus was developed independently by Newton and Leibniz.",
    "Derivatives measure rates of change.",
    "Integrals measure accumulated quantities.",
    "The fundamental theorem of calculus links derivatives and integrals.",
    "Linear algebra studies vectors and matrices.",
    "A matrix is a rectangular array of numbers.",
    "Eigenvalues are special numbers associated with matrices.",
    "Probability theory studies random events.",
    "Statistics is the science of data.",
    "The normal distribution is also called the bell curve.",
    "The mean is the average of a set of numbers.",
    "The median is the middle value in a sorted list.",
    "The mode is the most frequent value.",
    "Standard deviation measures how spread out data is.",
    # Technology extended
    "The first computer was mechanical.",
    "Charles Babbage designed the Analytical Engine.",
    "Ada Lovelace was the first computer programmer.",
    "Alan Turing is considered the father of computer science.",
    "The Turing Test checks if a machine can think.",
    "The first electronic computer was ENIAC.",
    "ENIAC was built in nineteen forty six.",
    "The transistor was invented in nineteen forty seven.",
    "The integrated circuit was invented in nineteen fifty eight.",
    "The microprocessor was invented in nineteen seventy one.",
    "The Intel four zero zero four was the first microprocessor.",
    "The personal computer became popular in the nineteen eighties.",
    "The Apple two was released in nineteen seventy seven.",
    "The IBM PC was released in nineteen eighty one.",
    "The Macintosh was released in nineteen eighty four.",
    "Windows was released in nineteen eighty five.",
    "Linux was created by Linus Torvalds in nineteen ninety one.",
    "The World Wide Web was invented by Tim Berners Lee.",
    "The first website went online in nineteen ninety one.",
    "Google was founded in nineteen ninety eight.",
    "Facebook was founded in two thousand four.",
    "The iPhone was released in two thousand seven.",
    "Cloud computing became mainstream in the twenty tens.",
    "Artificial intelligence research began in the nineteen fifties.",
    "Machine learning is a subset of artificial intelligence.",
    "Deep learning uses neural networks with many layers.",
    "Neural networks are inspired by the human brain.",
    "Backpropagation is the main training algorithm for neural networks.",
    "Transformers are a type of neural network architecture.",
    "Large language models use transformer architecture.",
    "GPT models are made by OpenAI.",
    "BERT is a model made by Google.",
    # Literature extended
    "Homer wrote the Iliad and the Odyssey.",
    "The Iliad is about the Trojan War.",
    "The Odyssey is about Odysseus journey home.",
    "Virgil wrote the Aeneid.",
    "Ovid wrote the Metamorphoses.",
    "Dante wrote the Divine Comedy.",
    "The Divine Comedy has three parts Inferno Purgatorio and Paradiso.",
    "Chaucer wrote the Canterbury Tales.",
    "Cervantes wrote Don Quixote.",
    "Don Quixote is considered the first modern novel.",
    "Shakespeare wrote thirty seven plays.",
    "Romeo and Juliet is a tragedy about two young lovers.",
    "Hamlet is about a prince who seeks revenge.",
    "Macbeth is about a Scottish lord who kills the king.",
    "King Lear is about a king who divides his kingdom.",
    "Moliere was a French playwright.",
    "Goethe wrote Faust.",
    "Victor Hugo wrote Les Miserables.",
    "Les Miserables is about the French underclass.",
    "Dickens wrote Oliver Twist and Great Expectations.",
    "Tolstoy wrote War and Peace.",
    "War and Peace is about Napoleonic Wars.",
    "Dostoevsky wrote Crime and Punishment.",
    "Hemingway wrote The Old Man and the Sea.",
    "Fitzgerald wrote The Great Gatsby.",
    "Orwell wrote nineteen eighty four.",
    "nineteen eighty four is about a totalitarian society.",
    "Tolkien wrote The Lord of the Rings.",
    "The Lord of the Rings is a fantasy epic.",
    "Rowling wrote the Harry Potter series.",
    # Philosophy extended
    "Socrates was sentenced to drink hemlock.",
    "Plato wrote dialogues featuring Socrates.",
    "The Republic is Platos most famous work.",
    "Aristotle was the tutor of Alexander the Great.",
    "Aristotle founded the Lyceum.",
    "Epictetus was a Stoic philosopher.",
    "Marcus Aurelius wrote Meditations.",
    "Augustine wrote the Confessions.",
    "Aquinas wrote the Summa Theologica.",
    "Machiavelli wrote The Prince.",
    "The Prince is about political power.",
    "Descartes said I think therefore I am.",
    "Spinoza wrote the Ethics.",
    "Leibniz developed calculus independently of Newton.",
    "Locke argued that the mind is a blank slate.",
    "Hume questioned the principle of causality.",
    "Kant wrote the Critique of Pure Reason.",
    "Hegel introduced the dialectic method.",
    "Nietzsche wrote Thus Spoke Zarathustra.",
    "Nietzsche declared that God is dead.",
    "Sartre wrote Being and Nothingness.",
    "Camus wrote The Myth of Sisyphus.",
    "Wittgenstein wrote the Tractatus.",
    # Music extended
    "Bach wrote the Brandenburg Concertos.",
    "Mozart wrote his first symphony at age eight.",
    "Beethoven went deaf but kept composing.",
    "Beethoven ninth symphony includes the Ode to Joy.",
    "Chopin wrote mostly for solo piano.",
    "Tchaikovsky wrote the Nutcracker ballet.",
    "Stravinsky wrote the Rite of Spring.",
    "Jazz originated in New Orleans.",
    "Louis Armstrong was a famous jazz musician.",
    "The Beatles were from Liverpool.",
    "Elvis Presley was called the King of Rock and Roll.",
    "Bob Dylan won the Nobel Prize in Literature.",
    "Michael Jackson was called the King of Pop.",
    # Art extended
    "The Mona Lisa is in the Louvre.",
    "The Mona Lisa was painted by Leonardo da Vinci.",
    "The Last Supper is a fresco by Leonardo.",
    "The Sistine Chapel was painted by Michelangelo.",
    "The Creation of Adam is part of the Sistine Chapel.",
    "The Starry Night was painted by Van Gogh.",
    "Van Gogh cut off his own ear.",
    "The Thinker is a sculpture by Rodin.",
    "David is a sculpture by Michelangelo.",
    "Guernica is a painting by Picasso.",
    "Picasso co founded Cubism.",
    "The Persistence of Memory is by Dali.",
    "The Birth of Venus is by Botticelli.",
    "The School of Athens is by Raphael.",
    "The Night Watch is by Rembrandt.",
    # Biology extended
    "The cell was discovered by Robert Hooke.",
    "The cell theory states that all living things are made of cells.",
    "Mitochondria have their own DNA.",
    "The mitochondria produce ATP.",
    "ATP is the energy currency of the cell.",
    "DNA was discovered by Friedrich Miescher.",
    "The double helix structure was discovered by Watson and Crick.",
    "Rosalind Franklin contributed to the discovery of DNA structure.",
    "The human genome was sequenced in two thousand three.",
    "The human genome has about twenty thousand genes.",
    "Evolution by natural selection was proposed by Darwin.",
    "Mendel discovered the laws of inheritance.",
    "Mutations are the source of genetic variation.",
    "A gene is a segment of DNA that codes for a protein.",
    "Proteins are made of amino acids.",
    "There are twenty standard amino acids.",
    "Enzymes are biological catalysts.",
    "Most enzymes are proteins.",
    "Photosynthesis converts sunlight into chemical energy.",
    "Chlorophyll is the green pigment in plants.",
    "Respiration converts glucose into ATP.",
    "The circulatory system transports blood.",
    "The nervous system transmits electrical signals.",
    "The digestive system breaks down food.",
    "The respiratory system exchanges gases.",
    "The excretory system removes waste.",
    "The endocrine system produces hormones.",
    "The immune system fights infections.",
    # Physics extended
    "Newton first law is the law of inertia.",
    "Newton second law is F equals m a.",
    "Newton third law is action equals reaction.",
    "Energy is conserved in isolated systems.",
    "Momentum is mass times velocity.",
    "Angular momentum is conserved.",
    "Entropy always increases in closed systems.",
    "The second law of thermodynamics is about entropy.",
    "Absolute zero is zero Kelvin.",
    "Absolute zero is minus two hundred seventy three Celsius.",
    "Light behaves as both wave and particle.",
    "The photoelectric effect was explained by Einstein.",
    "Electrons have wave properties.",
    "The uncertainty principle was formulated by Heisenberg.",
    "The Schrodinger equation describes quantum systems.",
    "Special relativity says time slows at high speeds.",
    "General relativity says gravity curves spacetime.",
    "E equals m c squared relates mass and energy.",
    "The speed of light is the same for all observers.",
    "Black holes are predicted by general relativity.",
    # Chemistry extended
    "The periodic table was devised by Mendeleev.",
    "The periodic table organizes elements by atomic number.",
    "Hydrogen is element number one.",
    "Helium is element number two.",
    "Carbon is element number six.",
    "Oxygen is element number eight.",
    "Iron is element number twenty six.",
    "Gold is element number seventy nine.",
    "Uranium is element number ninety two.",
    "Water boils at one hundred degrees Celsius.",
    "Water freezes at zero degrees Celsius.",
    "The pH scale ranges from zero to fourteen.",
    "Acids have pH less than seven.",
    "Bases have pH greater than seven.",
    "Pure water has a pH of seven.",
    "Hydrochloric acid is a strong acid.",
    "Sodium hydroxide is a strong base.",
    "Salt is sodium chloride.",
    "Baking soda is sodium bicarbonate.",
    "Vinegar is acetic acid.",
    # Astronomy extended
    "The solar system has eight planets.",
    "Mercury is the smallest planet.",
    "Venus is the hottest planet.",
    "Earth is the only planet with liquid water on its surface.",
    "Mars has the largest volcano in the solar system.",
    "Jupiter has at least seventy nine moons.",
    "Saturn rings are made of ice and rock.",
    "Uranus is tilted on its side.",
    "Neptune has the strongest winds in the solar system.",
    "The Moon is moving away from Earth at about four centimeters per year.",
    "A solar eclipse happens when the Moon blocks the sun.",
    "A lunar eclipse happens when Earth blocks the sun light to the Moon.",
    "The sun is about four point six billion years old.",
    "The sun will become a red giant in about five billion years.",
    "A light year is about nine trillion kilometers.",
    "The nearest star is Proxima Centauri.",
    "Proxima Centauri is about four light years away.",
    "The Milky Way has about two hundred billion stars.",
    "The universe has about two trillion galaxies.",
    "The cosmic microwave background is the afterglow of the Big Bang.",
    # Daily life extended
    "Coffee is one of the most popular drinks in the world.",
    "Coffee contains caffeine which is a stimulant.",
    "Tea is the most consumed beverage after water.",
    "Tea originated in China.",
    "Wine is made from fermented grapes.",
    "Beer is one of the oldest alcoholic drinks.",
    "Bread is a staple food in many cultures.",
    "Rice is a staple food in Asia.",
    "Pasta originated in Italy.",
    "Pizza originated in Naples Italy.",
    "Cheese is made from milk.",
    "Yogurt is made by fermenting milk.",
    "Chocolate is made from cacao beans.",
    "Chocolate was first used in Mesoamerica.",
    "Salt enhances flavor and preserves food.",
    "Sugar is extracted from sugar cane or sugar beets.",
    "Honey is produced by bees from flower nectar.",
    "Eggs are rich in protein.",
    "Meat is a major source of protein.",
    "Fish is rich in omega three fatty acids.",
    "Vegetables provide vitamins and minerals.",
    "Fruits are usually sweet and contain seeds.",
    "Nuts are rich in healthy fats.",
    "Beans are a good source of plant protein.",
    "Rice is the staple food of half the world population.",
    "Wheat is used to make bread and pasta.",
    "Corn is also called maize.",
    "Potatoes are native to the Andes.",
    "Tomatoes are native to South America.",
    "Peppers are native to the Americas.",
]


def _get_mega_facts():
    """Returns the mega facts list."""
    return _MEGA_FACTS
